// max is rand % max
// but what's min?
// i dont care i will just use the max macro
// but then the min value will appeare more often.
//int rnd = MAX(4, rand() % 20);
// i thought i would max need because ascii have unprintable chars
// but I could just create an array


#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <math.h>
#include <unistd.h>
#include <sys/time.h>
//#include <string.h>

#define MAX(A, B) (((A)<(B)) ? (B) : (A))
#define MAXPASSWORDLENGTH 15
#define LIMIT 82
#define DEBUG 0

int main(int argc, char** argv) {
    // generated by chat-gpt
    char arr_input[83] =
"ABCDEFGHIJKLMNOPQRSTUVWXYZ" // 26 chars
"abcdefghijklmnopqrstuvwxyz" // same
"0123456789" // 10
"!#$%^*()-_=+[]{}`,.?"; // 20


    int LENGTH = atoi(argv[1]);
    if (LENGTH > MAXPASSWORDLENGTH) {
         perror("length is too big! (max:15)");
         return 1;
    }

    


    char buff[MAXPASSWORDLENGTH]={};
    struct timeval tv;
    gettimeofday(&tv, NULL);
    srand(tv.tv_usec * tv.tv_sec);

    for (int i = 0; i < LENGTH; i++) {
        if (i == LENGTH-1) { buff[i] = '\0'; }
        int r = rand() % LIMIT;
        int rnd = MAX(0, r);
        buff[i]=(char)arr_input[rnd];
        //printf("%c", arr_input[rnd]);
    }

      // set sepcial caracters at B&E
    // At index 62 starting special char's
    //buff[0]        = buff[get_rnd(char_offset)];
    //buff[LENGTH-1] = buff[get_rnd(char_offset)];
    const int offset = 1, char_offset = 62;
    int indexA = 0;
    int indexB = 0;
            
    do {
        indexA=char_offset+rand() % LIMIT;
        indexB=char_offset+rand() % LIMIT;
        #if DEBUG == 1
        printf("\n--DEBUG B: %d != %d--\n", indexA, indexB);
        sleep(1);
        #endif
    } while (indexA == indexB); // first and last should not be the same
    buff[0]        = arr_input[indexA];
    buff[LENGTH-1] = arr_input[indexB];


    printf("Generated Password: %s\n", buff);

    return 0;
}
